[package]
name = "rust_music_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = []
default = ["wasm"]
